### ISSUE TITLE
Calling .Sample() on a MaterialParameter array index crashes Unity

### ISSUE THREAD

**Issue by ComeOnAndSam** [Unity-Technologies/com.unity.perception#327]
I have the following randomizer script, a script meant to randomize the material on gameobjects in my scene, using multiple sets of MaterialParameters from an array to be applied to different sets of gameobjects. 

![image](https://user-images.githubusercontent.com/47126678/120366205-64d25900-c2dd-11eb-93fe-cade7c307571.png)

Here's what the code looks like up to the point where it crashes.

```
public class UniformMaterialRandomizer : Randomizer
{
    public MaterialParameter[] Materials;

    /// <summary>
    /// Sets every tagged object to the same randomly selected material of the correct set
    /// </summary>
    protected override void OnIterationStart()
    {
        var tags = tagManager.Query<UniformMaterialRandomizerTag>();
       
        for(int i = 0; i < Materials.Length; i++)
        {
            Material newMat = Materials[i].Sample();
        }
    }
}
```

The line "Material newMat = Materials[i].Sample();" is where the crash occurs. 

There is a lot of complexity in how my scene is set up, but I've been very thorough with debugging and disabling and everything seems to be in order. My best guess at this point is something is wrong with .Sample() that causes a crash when sampling under this condition.

**Comment by mkamalza** [comment]
I tried your code with some sample materials I have and did not face any issues. Do you get any errors in the console or does Unity crash completely? In the latter case, you could check the log file to see if any helpful logs are written.
The location of the log file can be found according to this: https://docs.unity3d.com/Manual/LogFiles.html

**Comment by JonathanHUnity** [comment]
@ComeOnAndSam This issue may be fixed on master. Feel free to try it out by installing the package again via the github repository, https://github.com/Unity-Technologies/com.unity.perception

**Comment by ComeOnAndSam** [comment]
@mkamalza @JonathanHUnity Sorry for forgetting to get back to you and thanks for looking into it. Unity just straight up crashes. I just encountered the error in a new place while calling ColorRGBCategorizedParamter.sample() when the paramter is a dictionary value, but it worked on a version that wasn't in a dictionary in a different script.

Sadly, this new master package does not change anything.

Here is my log files, though they seem to say that they couldn't grab the needed information.

[upm.log](https://github.com/Unity-Technologies/com.unity.perception/files/6743094/upm.log)
[Editor-prev.log](https://github.com/Unity-Technologies/com.unity.perception/files/6743095/Editor-prev.log)
[Editor.log](https://github.com/Unity-Technologies/com.unity.perception/files/6743096/Editor.log)

**Comment by JonathanHUnity** [comment]
Thanks for the logs. I notice that you are using an older version of 2020.2. The next step I would suggest is updating to the latest version of 2020.3, as crashes like this in the engine are commonly addressed in later versions.

**Comment by ComeOnAndSam** [comment]
> 
> 
> Thanks for the logs. I notice that you are using an older version of 2020.2. The next step I would suggest is updating to the latest version of 2020.3, as crashes like this in the engine are commonly addressed in later versions.

So, interestingly, I upgraded to 2020.3.13f1, I ran the needed script (SurfaceAndColorRandomizer) twice and it worked without issue, and then without changing that script at all, Unity once again started crashing every time I start the scene with that script active.

Here's the logs again plus my crash log.

[(Crash log) Editor.log](https://github.com/Unity-Technologies/com.unity.perception/files/6749732/Crash.log.Editor.log)
[error.log](https://github.com/Unity-Technologies/com.unity.perception/files/6749734/error.log)
[Editor.log](https://github.com/Unity-Technologies/com.unity.perception/files/6749735/Editor.log)
[upm.log](https://github.com/Unity-Technologies/com.unity.perception/files/6749736/upm.log)

**Comment by ComeOnAndSam** [comment]
Oops, I deleted a comment where I gave logs because it turns out I didn't properly upgrade the package. However, I now am sure it's upgraded to the master version, and unity 2020.3.13f1, and the issue is still ocurring. Here are the latest logs.

[upm.log](https://github.com/Unity-Technologies/com.unity.perception/files/6766182/upm.log)
[Editor.log](https://github.com/Unity-Technologies/com.unity.perception/files/6766180/Editor.log)
[Editor-prev.log](https://github.com/Unity-Technologies/com.unity.perception/files/6766181/Editor-prev.log)

And the crash log
[error.log](https://github.com/Unity-Technologies/com.unity.perception/files/6766184/error.log)
[Editor.log](https://github.com/Unity-Technologies/com.unity.perception/files/6766185/Editor.log)

**Comment by ComeOnAndSam** [comment]
yeah same issue on the official package release. I upgraded, it ran twice successfully, and then crashed Unity forever after that.

**Comment by StevenBorkman** [comment]
@ComeOnAndSam I'm sorry that we let this issue fall off our radar. I'm going to have time to look into this early next week, but I wanted to make sure that you are still experiencing this issue before I dig in.

**Comment by ComeOnAndSam** [comment]
> 
> 
> @ComeOnAndSam I'm sorry that we let this issue fall off our radar. I'm going to have time to look into this early next week, but I wanted to make sure that you are still experiencing this issue before I dig in.

It appears that the latest release of of the perception package has fixed the issue, so I'll mark this as closed.
