### ISSUE TITLE
Can't find Dataset Visualizer in Window pannel

### ISSUE THREAD

**Issue by VirajVaitha123** [Unity-Technologies/com.unity.perception#506]
Hi,

I was trying to use the dataset visualizer by following the tutorial but can't see the option in Unity.

I am using version 2020.2.7f1 and have signed into Unity. (Perception version = 0.8.0-preview-4)

![image](https://user-images.githubusercontent.com/44236859/173540456-9960aa9f-4016-4aa0-9b84-c0d725621ef8.png)

I also don't see perception in the project settings window, maybe this is linked?
![image](https://user-images.githubusercontent.com/44236859/173541054-2d8e590c-8051-4c9c-b60b-a32fb1599ec2.png)

Please can someone help with this

Thanks,

Viraj

**Comment by RuiyuZ** [comment]
Hi @VirajVaitha123 

The dataset visualizer was not included in the perception package version 0.8.0-preview4. Is there any specific reason you want to use this version of the package?

I would suggest upgrading the perception package to the latest version of 0.11.2-preview.2, it includes the dataset visualizer and many more updated functionality. The upgrade can be done via:

**Windows -> Package Manager -> Perception -> update to 0.11.2-preview.2**

Let me know if there are more issues!

Best,
Ruiyu

**Comment by MrVBian** [comment]
Hi @RuiyuZ 

![image](https://user-images.githubusercontent.com/37790267/175253160-64512ec9-2695-40a2-b707-1dad27cf2ff9.png)

I am using version 2020.3.32f1. (Perception version = 0.11.1-preview.1)

Unfortunately, WHEN I tried Open Visualizer, I got the following error: 

```
Failed to get visualizer process ID after launch. Note that this does not necessarily mean the tool did not launch successfully. However, running the visualizer again will now create a new instance of the process.
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()
```

Look forward to hearing from you

Best,
ZhenweiBian

**Comment by RuiyuZ** [comment]
Hi @MrVBian,

There was an issue with the dataset visualizer in perception version 0.11.1-preview.1, if you update the package to the latest version 0.11.2-preview.2, it should fix the issue. Thanks!

Best,
Ruiyu

**Comment by rich-sz** [comment]
> 

hi @RuiyuZ 
I just had the same problem like @MrVBian , I'm using the Perception version = 0.11.1-preview.2, and unity version=2021.3.4f1c1. At first, I suspect the unity version, so I switch to the older unity version= 2020.3.36f1c1, but this problem is still there( I didn't do the privious step, just open the Visulizer derectly in older version).
![image](https://user-images.githubusercontent.com/37059752/177526277-4d8f8b30-a9e4-45e9-a969-af11da34a750.png)
![image](https://user-images.githubusercontent.com/37059752/177527621-cc0a957f-0099-4b81-85f3-6547faad1655.png)

**Comment by Maru-prono** [comment]
Hi @rich-sz 
This is caused by version of protobuf.
![1](https://user-images.githubusercontent.com/107236755/181411720-d27304c8-278a-4373-8378-c72f44596a81.png)

I could fix to __downgrade protobuf version__.
I show how to solve it.

__UnityVersion=2021.3.6f1__
__PerceptionVersion = 0.11.2-preview.2__

## 1. Download DatasetVisualizer
Install DatasetVisualizer selecting `Window -> DatasetVisualizer -> Open`.

![2](https://user-images.githubusercontent.com/107236755/181418386-425aa647-897d-4b26-8b73-34b68f262abf.png)
A few minutes later,  you can see 2 messages.

![3](https://user-images.githubusercontent.com/107236755/181418666-fb8b9980-edf2-455d-9015-33ee43ab05a5.png)

## 2. Open Powershell
Open Powershell selecting `Edit -> Project Settings -> Python for Unity -> Spawn shell in environment`.

![4](https://user-images.githubusercontent.com/107236755/181418908-9027aa1a-31e6-4890-a37a-5f2ff818dc05.png)

## 3. Update "pip"
Enter command `pip install --upgrade pip`.

![3](https://user-images.githubusercontent.com/107236755/181419945-b9134688-3180-4e71-acef-a0906081cd7d.png)

## 4. Downgrade "protobuf"
Enter command `pip install 'protobuf<3.20'`.

![4](https://user-images.githubusercontent.com/107236755/181420044-f8e881ee-3e8c-4bbf-a0d6-02b0436addb8.png)

After Installing packages, you can close Powershell.

## 5. Open DatasetVisualizer
Select `Window -> DatasetVisualizer -> Open`. I think you can open DatasetVisualizer.

Best,

**Comment by aryan-mann** [comment]
Hey all! The Perception team just released 🎉 Perception 1.0 🎉, a major update to the toolset! With this new release, we have deprecated the dataset visualizer in favor of a more readable output format called SOLO and a python toolchain for visualization and processing called pysolotools. More details here: [Perception 1.0: Expanding the Open Source Toolbox for Synthetic Data](https://blog.unity.com/technology/perception-open-source-toolbox-for-synthetic-data)

We recommend hopping on over to using SOLO + pysolotools instead! It should be as easy as just changing the output format and installing the pysolotools python package.

Closing this for now, feel free to open it back up if there are any issues.
